config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|vi/ do
    resources :items, only: [:new, :show, :create]

    post '/cart_items' => 'cart_items#create', as: :cart_items
    delete '/cart_items' => 'cart_items#destroy'

    get '/carts/proceed_checkout' => 'carts#proceed_checkout', as: :proceed_checkout
    get '/carts/' => 'carts#show', as: :cart
    put '/carts/' => 'carts#update'
    delete '/carts/' => 'carts#destroy'

    get '/order/create' => 'orders#create', as: :order_create
    resources :orders, except: :create

    resources :searches, only: :index

    resources :categories

    resources :advertisements, only: :index

    root 'categories#index'
  end
end

app/models/category.rb
class Category
  include Mongoid::Document	
  include Mongoid::Timestamps

  field :id, type: Integer
  field :name, type: String
  field :keyword, type: String

  has_many :items, dependent: :destroy
  validates :name, uniqueness: :true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @recommended_items = Item.recommended(6)
    @newest_items = Item.newest(4)
  end

  def show
    @category = Category.includes(:items).find_by(id: params[:id])
    @items = @category.items.page(params[:page])  
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_parts/_catalog.html.erb
<div class="row ">
  <div class="header_catalog col-md-offset-0 col-md-5 ">
    Category
  </div>
</div>
<br />
<% categories.each do |category| %>
  <div class="row">
    <p> <%= link_to category.name, category_path(id: category.id) %> </p>
  </div>
<% end %>
<div class="row">
    <p> <%= link_to "Advertisement", advertisements_path %> </p>
</div>

app/views/categories/_parts/_category_item.html.erb
<div class="row">
  <div class="col-sm-6 col-md-3">
    <div class="thumbnail">
      <img src="<%= category_item.picture_url%>" class="image">
    </div>
  </div>
  <div class="col-md-9 col-md-offset-0">
    <%= link_to category_item.name, item_path(locale, category_item.id) %>
    <br />
    <strong> Price </strong>: $<%= category_item.price%>
    <br />
    <% unless user_signed_in? && (current_user.role == User.role_users[:admin])%>
      <% if category_item.stock > 0 %>
        <%= render 'items/_parts/add_to_cart', {item_id: category_item.id,
                                                stock: category_item.stock,
                                                hidden_quantity: true
                                                }%>
      <% else %>
        <div class="out_of_stock">
          Out of stock
        </div>
      <% end %>
    <% else %>
      Stock: <span class="out_of_stock"><%= category_item.stock %></span>
    <% end %>
  </div>
</div>

app/views/categories/_parts/_category_items.html.erb
<div class="row">
  <div class="header_catalog col-md-offset-0 col-md-12 ">
    <%= category.name %>
  </div>
</div>
<br />
<div class="recommened_list">
  <%= render partial: 'categories/_parts/category_item', collection: category_items,	
  					 locale: @locale%>
</div>

app/views/categories/_parts/_newest_item.html.erb
<div class="row">
  <div class="col-sm-6 col-md-2">
    <div class="thumbnail">
      <img src="<%= newest_item.picture_url%>" class="image">
    </div>
  </div>
  <div class="col-md-9 col-md-offset-0">
    <%= link_to newest_item.name, item_path(id: newest_item.id) %>
    <br />
    <strong> Price </strong>: $<%= newest_item.price %>
  </div>
</div>

app/views/categories/_parts/_newest_items.html.erb
<div class="row">
  <div class="header_catalog col-md-offset-0 col-md-12 ">
    Newest Items
  </div>
</div>
<br />
<br />
<div class="newest_list row">
  <%= render partial: 'categories/_parts/newest_item', collection: newest_items %>
  <br />
</div>

app/views/categories/_parts/_recommended_item.html.erb
<div class="col-sm-6 col-md-4">
  <div class="col-md-12">
    <%= recommended_item.name %>
  </div>
  <div class="col-md-12">
    <%= link_to(image_tag(recommended_item.picture_url, width: 38, height: 71),
      item_path(id: recommended_item.id)) %>
  </div>
</div>

app/views/categories/_parts/_recommended_items.html.erb
<div class="row">
  <div class="header_catalog col-md-offset-0 col-md-12 ">
    Recommended Items
  </div>
</div>
<br />
<div class="recommended_list row">
  <%= render partial: 'categories/_parts/recommended_item', collection: recommended_items %>
  <br />
</div>