config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|vi/ do
    resources :items, only: [:new, :show, :create]

    post '/cart_items' => 'cart_items#create', as: :cart_items
    delete '/cart_items' => 'cart_items#destroy'

    get '/carts/proceed_checkout' => 'carts#proceed_checkout', as: :proceed_checkout
    get '/carts/' => 'carts#show', as: :cart
    put '/carts/' => 'carts#update'
    delete '/carts/' => 'carts#destroy'

    get '/order/create' => 'orders#create', as: :order_create
    resources :orders, except: :create

    resources :searches, only: :index

    resources :categories

    resources :advertisements, only: :index

    root 'categories#index'
  end
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  belongs_to :user
  has_many :cart_items, dependent: :destroy

  def convert_to_array_of_hash
    cart_items.map do |cart_item|
      {
        item: cart_item.item,
        quantity: cart_item.quantity.to_i
      }
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CartConcern

  def show
    enough_stock_to_sale_and_reload_cart?(@cart)
    @cart_items = if user_signed_in?
                    @cart.convert_to_array_of_hash
                  else
                    @cart.map do |item_id, quantity|
                      {
                        item: Item.find_by(id: item_id.to_i),
                        quantity: quantity.to_i
                      }
                    end
                  end
    @cart_subtotal = get_subtotal(@cart_items)
    @reload = params[:reload].present?
  end

  def update
    respond_to do |format|
      @cart_subtotal = params[:quantity][:subtotal].to_f
      @cart_item_quantity = params[:quantity][:quantity].to_i
      @item = Item.find_by(id: params[:quantity][:item_id].to_i)
      if user_signed_in?
        item_cart = CartItem.find_by(cart_id: @cart.id, item_id: @item.id)
        @cart_subtotal = subtotal_after_update_quantity(@cart_subtotal,
                                                        @item.price,
                                                        item_cart.quantity,
                                                        @cart_item_quantity
                                                        )
        item_cart.update_column(:quantity, @cart_item_quantity )
      else
        @cart_subtotal = subtotal_after_update_quantity(@cart_subtotal,
                                                        @item.price,
                                                        @cart["#{@item.id}"],
                                                        @cart_item_quantity
                                                        )
        @cart["#{@item.id}"] = @cart_item_quantity
        # store_cart_to_cookie(@cart)
        store_cart_to_session(@cart)
      end
      format.html {}
      format.js {}
    end
  end


  def proceed_checkout
    respond_to do |format|
      @enough_stock = enough_stock_to_sale_and_reload_cart?(@cart)
      format.html {}
      format.js {}
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def get_cart_quantity(cart)
    quantity = 0
    if cart.class == Cart
      cart.cart_items.each do |cart_item|
        quantity += cart_item.quantity.to_i
      end
    else
      quantity = cart.values.sum
    end
    quantity
  end
end

app/views/carts/_parts/_cart_item.html.erb
<div class="row">
  <div class="col-md-offset-0 col-md-1">
    <%= link_to({controller: "items", action:"show", id: cart_item[:item].id}) do %>
      <img src="<%= cart_item[:item].picture_url %>"
        height="71px" width="38px">
    <% end %>
  </div>
  <div class="col-md-offset-0 col-md-6">
    <div>
      <%= link_to cart_item[:item].name, item_path(locale, cart_item[:item].id) %>
    </div>
    <br />
    <div>
      <%= link_to "Delete", cart_items_path(locale, item_id: cart_item[:item].id), method: :delete %>
    </div>
  </div>
  <div class="col-md-offset-0 col-md-3">
    <span class="price">
      $<%= cart_item[:item].price%>
    </span>
  </div>
  <div class="col-md-offset-0 col-md-2">
    <%= form_for("quantity", url: cart_path, method: :put, remote: true) do |f| %>
      <%= f.hidden_field :item_id, value: cart_item[:item].id %>
      <%= f.hidden_field :subtotal, value: cart_subtotal, class: "subtotal_quantity" %>
      <% if cart_item[:item].stock > 30 %>
        <%= f.select :quantity, 1..30, {selected: cart_item[:quantity]},
          {id: "quantity_#{cart_item[:item].id}", onchange: "$(this).closest('form').submit();"} %>
      <% else %>
        <%= f.select :quantity, 1..cart_item[:item].stock, {selected: cart_item[:quantity]},
          {id: "quantity_#{cart_item[:item].id}", onchange: "$(this).closest('form').submit();"} %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/carts/_parts/_cart_items.html.erb
<div class="row">
  <div class="header_catalog col-md-offset-0 col-md-12 ">
    Shopping Cart
  </div>
</div>
<br />
<% if reload %>
  <div id="alert-cart">
    <div class="alert alert-danger">Not enough item in stock. Therefore must be reload cart!</div>
  </div>
<% end %>
<div class="recommened_list col-md-offset-1 col-md-9">
  <div class="row">
    <div class="col-offset-0 col-md-7">
    </div>
    <div class="col-offset-0 col-md-2">
      <strong> Price </strong>
    </div>
    <div class="quantity col-offset-0 col-md-3">
      <strong> Quantity </strong>
    </div>
  </div>
  <hr/>
  <%= render partial: 'carts/_parts/cart_item', collection: cart_items, locals: {cart_subtotal: cart_subtotal, locale: @locale} %>
  <hr/>

  <div class="row">
    <div class="col-md-offset-0 col-md-7">
    </div>
    <div class="subtotal col-md-offset-0 col-md-5">
      <strong>Subtotal (<span id="count_items"> <%= get_cart_quantity(cart) %> items </span>):</strong>
      <span class="price" id="subtotal"> $<%= cart_subtotal %> </span>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-0 col-md-7">
    </div>
    <div class="col-md-offset-0 col-md-5">
      <% if cart_items.present? %>
        <% if user_signed_in? %>
          <%= link_to "Checkout", proceed_checkout_path, method: :get, remote: true,
            class: "btn checkout2", data: { confirm: 'Are you sure?' } %>
        <% else %>
          <%= link_to "Proceed to checkout", new_user_session_path, class: "btn checkout"%>
        <% end %>
      <% end %>
    </div>
  </div>
</div>