config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|vi/ do
    resources :items, only: [:new, :show, :create]

    post '/cart_items' => 'cart_items#create', as: :cart_items
    delete '/cart_items' => 'cart_items#destroy'

    get '/carts/proceed_checkout' => 'carts#proceed_checkout', as: :proceed_checkout
    get '/carts/' => 'carts#show', as: :cart
    put '/carts/' => 'carts#update'
    delete '/carts/' => 'carts#destroy'

    get '/order/create' => 'orders#create', as: :order_create
    resources :orders, except: :create

    resources :searches, only: :index

    resources :categories

    resources :advertisements, only: :index

    root 'categories#index'
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :category
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  attr_accessor :picture
  mount_uploader :picture, PictureUploader,
                 cloudinary_credentials:
                  Proc.new { |a| a.instance.cloudinary_credentials }

  validates :name, presence: true
  validates :price, presence: true
  validates :stock, presence: true
  validates :description, presence: true
  validates :picture, presence: true
  validate :picture_size_validation

  paginates_per Settings.entries_per_page

  scope :recommended, -> (limit) { order("updated_at desc").limit(limit) }
  scope :newest, -> (limit) { order("created_at desc").limit(limit) }

  def cloudinary_credentials
    {
      cloud_name: ENV['cloud_name'],
      api_key: ENV['api_key'],
      api_secret: ENV['api_secret']
    }
  end

  private

  def picture_size_validation
    errors[:picture] << "should be less than 5MB" if picture.size > 5.megabytes
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    new_item_param = post_item_params
    category = Category.find_by(name: new_item_param[:category])
    new_item_param[:category_id] = category.id
    new_item_param.delete('category')
    @item = Item.new(new_item_param)

    if @item.save
      flash.now[:success] = 'Post successful'
      redirect_to item_path(@item.id)
    else
      render 'new'
    end
  end

  def show
    @item = Item.find_by(id: params[:id])
  end

  private

  def post_item_params
    params.require(:post_item).permit(:name,
                                      :price,
                                      :stock,
                                      :category,
                                      :description,
                                      :picture
                                      )
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/new.html.erb
<%= render 'layouts/_parts/meta_tags', {title: "New Item", keywords: ["new", "item"],
                                        description: nil
                                        } %>
<div class="container">
  <div class="row">
    <div class="col-md-offset-0 col-md-4">
      <%= link_to "Home", root_path%> > Posting Item
    </div>
  </div>
  <br />
  <div class="login">
    <% flash.each do |key, value| %>
       <div class="alert alert-danger"><%= value %></div>
    <% end %>
  </div>
  <br>
  <div class="row">
    <div class="col-md-8 col-md-offset-5">
      <h1 style="text-align:auto"> Post New Item</h1>
    </div>
    <div class="col-md-6 col-md-offset-3">
      <% if @item.errors.any? %>
        <div id="errors">
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for(:post_item, url: items_path, method: :post, html:{multipart: true}) do |f| %>
        <div class="field">
          <%= f.label :name_item%><br />
          <%= f.text_field :name, autofocus: true, class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :price%><br />
          <%= f.number_field :price, :step => "0.01", autocomplete: "off", class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :stock%><br />
          <%= f.number_field :stock, min: 0, autocomplete: "off", class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :category%><br />
          <%= f.select :category, options_for_select(@categories.map{|cate| cate.name}),
            autocomplete: "off", class: 'form-control' %>
        </div>

        <div class="field">
          <%= f.label :Picture %>
          <%= f.file_field :picture, class: 'form-control' %> <br/>
        </div>

        <div class="field">
          <%= f.label :description%><br />
          <%= f.text_area :description, class: 'form-control' %>
        </div>

        <div class="actions">
          <br />
          <%= f.submit "Post", class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<%= render 'layouts/_parts/meta_tags', {title: "Item #{@item.id}",
                                        keywords: ["new", "item"],
                                        description: @item.description} %>
<div class="container">
  <div class="row">
    <div class="col-md-offset-0 col-md-4">
      <%= link_to "Home", root_path %> >
      <%= link_to @item.category.name, category_path(@locale, @item.category.id) %>
      > Items ID <%= @item.id %>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-md-offset-0 col-md-3">
      <%= render "categories/_parts/catalog", { categories: @categories} %>
    </div>
    <div class="col-md-offset-0 col-md-9">
      <div class="row">
        <div class="col-md-offset-0 col-md-3">
          <img src="<%= @item.picture_url %>"
            height="110px" width="86px">
        </div>
        <div class="col-md-offset-0 col-md-9">
          <div class="row">
            <strong> Item ID: </strong> <%= @item.id %>
          </div>
          <div class="row">
            <strong> Price: </strong> $<%= @item.price %>
          </div>
          <div class="row">
            <strong> Date: </strong> <%= @item.updated_at.strftime("%Y-%m-%d") %>
          </div>
          <div class="row">
            <% unless user_signed_in? && current_user.admin? %>
              <% if @item.stock > 0 %>
                <%= render "items/_parts/add_to_cart", {stock: @item.stock, item_id: @item.id,
                  hidden_quantity: nil} %>
              <% else %>
                <div class="out_of_stock">
                  Out of stock
                </div>
              <% end %>
            <% else %>
              Stock: <span class="out_of_stock"><%= @item.stock %></span>
            <% end %>
          </div>
        </div>
      </div>
      <br />
      <div class="row description">
        <strong>Description</strong>:
        <br />
        <%= @item.description %>
      </div>
      <br />
      <div class="row">
        <%= render 'items/_parts/share', {item: @item}%>
      </div>
    </div>
  </div>
</div>